//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olga.Resources.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be informed that  new Procedure was created in Pharma Database.
        /// </summary>
        internal static string BodyProcedureCreate {
            get {
                return ResourceManager.GetString("BodyProcedureCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be informed that Procedure for (name) was updated.
        /// </summary>
        internal static string BodyProcedureUpdate {
            get {
                return ResourceManager.GetString("BodyProcedureUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be informed that  new product (name)  was created in Pharma Database!.
        /// </summary>
        internal static string BodyProductCreate {
            get {
                return ResourceManager.GetString("BodyProductCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be informed that section (name) was updated.
        /// </summary>
        internal static string BodyProductUpdate {
            get {
                return ResourceManager.GetString("BodyProductUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;&lt;br&gt;With best regards,&lt;br&gt;
        ///Sent from Regulatory Affairs Database.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification about new procedure was created in Pharma Database for (name).
        /// </summary>
        internal static string SubjectProcedureCreate {
            get {
                return ResourceManager.GetString("SubjectProcedureCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification about procedure updates in Pharma Database for (name).
        /// </summary>
        internal static string SubjectProcedureUpdate {
            get {
                return ResourceManager.GetString("SubjectProcedureUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification about new product (name) was created in Pharma Database.
        /// </summary>
        internal static string SubjectProductCreate {
            get {
                return ResourceManager.GetString("SubjectProductCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification about product (name) updates in Pharma Database.
        /// </summary>
        internal static string SubjectProductUpdate {
            get {
                return ResourceManager.GetString("SubjectProductUpdate", resourceCulture);
            }
        }
    }
}
