//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olga.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not send! Can not detect the product for procedure!.
        /// </summary>
        public static string EmailNotSendCantFindProdToProc {
            get {
                return ResourceManager.GetString("EmailNotSendCantFindProdToProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened!.
        /// </summary>
        public static string ErrorHappened {
            get {
                return ResourceManager.GetString("ErrorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No countryId in request!.
        /// </summary>
        public static string NoCountryId {
            get {
                return ResourceManager.GetString("NoCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file to load!.
        /// </summary>
        public static string NoFileToLoad {
            get {
                return ResourceManager.GetString("NoFileToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Id in request!.
        /// </summary>
        public static string NoIdInRequest {
            get {
                return ResourceManager.GetString("NoIdInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions for this operation!.
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to requested recource!.
        /// </summary>
        public static string NoPermissionToRecource {
            get {
                return ResourceManager.GetString("NoPermissionToRecource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t have Products! So there are no Procedures to work with!.
        /// </summary>
        public static string NoProcCauseNoProd {
            get {
                return ResourceManager.GetString("NoProcCauseNoProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not correct login/password.
        /// </summary>
        public static string NotCorrectLogin {
            get {
                return ResourceManager.GetString("NotCorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product deleted successfully!.
        /// </summary>
        public static string ProductDeleteSuccess {
            get {
                return ResourceManager.GetString("ProductDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting for country already exists!.
        /// </summary>
        public static string SettingAlreadyExists {
            get {
                return ResourceManager.GetString("SettingAlreadyExists", resourceCulture);
            }
        }
    }
}
