//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olga.Resources.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries settings.
        /// </summary>
        public static string CountrySettings {
            get {
                return ResourceManager.GetString("CountrySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Country Setting.
        /// </summary>
        public static string CreateCountrySetting {
            get {
                return ResourceManager.GetString("CreateCountrySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Procedure.
        /// </summary>
        public static string CreateProcedure {
            get {
                return ResourceManager.GetString("CreateProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Procedure for.
        /// </summary>
        public static string CreateProcedureFor {
            get {
                return ResourceManager.GetString("CreateProcedureFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Country Setting.
        /// </summary>
        public static string EditCountrySetting {
            get {
                return ResourceManager.GetString("EditCountrySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product Additional Files.
        /// </summary>
        public static string EditProductAdditionalFiles {
            get {
                return ResourceManager.GetString("EditProductAdditionalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
    }
}
